export default {
    filmGrid: document.querySelector('.film__grid'),
    preloader: document.querySelector('.preloader'),
    searchError: document.querySelector('.search-error'),
    homeBtn: document.querySelector('.js-home-btn'),
    libraryBtn: document.querySelector('.js-library-btn'),
    headerHome: document.querySelector('.section__header'),
    headerLibrary: document.querySelector('.my__library'),  // wrong!!! it will be undefined
    libraryBtns: document.querySelector('.library'),
    btnWatched: document.querySelector('.js-btn-watched'),
    btnQueue: document.querySelector('.js-btn-queue'),
    searchInput: document.querySelector('.header__search'),
    btnCloseModal: document.querySelector('[data-action="close-popap"]'),
    modalContentBox: document.querySelector('[data-film="popap"]'),
    backdropBox: document.querySelector('.popap'),
    btnCloseSvg: document.querySelector('.popap__svg-close'),
    headerWatchedBtn: document.querySelector('.js-btn-watched'),
    headerQueueBtn: document.querySelector('.js-btn-queue'),
    fetchTrendingMoviesToggle: document.querySelector('.switch-button'),
    fetchTrendingMoviesBtn: document.querySelector('.switch-button-checkbox'),
    openModalBtnFooter: document.querySelector("[data-footer-modal-open]"),
    closeModalBtnFooter: document.querySelector(".data-footer-modal-close-button"),
    modalFooter: document.querySelector(".footer-backdrop"),
    openCardsCommandBtn: document.querySelector('.collapsible'),    
    contentCommandCards: document.querySelector('.content'),    
    closeCardsCommandBtn: document.querySelector('.data-user-close-button'),
    genreSorter: document.querySelector('.genre-modal'),
    genresBtn: document.querySelector('.value-btn'),
    searchNav: document.querySelector('.search-nav'),
    genresList: document.querySelector('.genres-list'),
    genresSection: document.querySelector('.genres-section'),
    switchersContainer: document.querySelector('.switchers'),
    genreBtn: document.querySelector('.genreBtn'),
    genreLi: document.querySelector('.button-genre'),
    body: document.querySelector('body'),
}

